### ISSUE TITLE
search results have different host component in their link

### ISSUE THREAD

**Issue by a-tze** [voc/media.ccc.de#1]
Search results have links beginning with https://api.media.ccc.de instead of https://media.ccc.de

Example: https://media.ccc.de/search/?q=bleed

**Comment by florolf** [comment]
This problem originates in the media API, which is used to create the search database (see https://github.com/voc/media-search-prototype/blob/master/server/media-import.pl): The `frontend_link` it supplies already contains the `api.` prefix.

@mm: Could you fix this?

**Comment by manno** [comment]
@florolf Thanks for finding this. I believe it's fixed now.
