### ISSUE TITLE
Public + Private API: Allow event lookup via uuid

### ISSUE THREAD

**Issue by saerdnaer** [voc/media.ccc.de#100]
Currently users of the APIs have to look up the internal media event id to request information, compare:
* https://github.com/voc/media.ccc.de/blob/master/app/controllers/public/events_controller.rb#L11
* https://github.com/voc/media.ccc.de/blob/master/app/controllers/api/events_controller.rb#L10

@manno: Can we add some heuristic, which checks if the id parameter is actually an Integer or looks like a uuid, and then use this uuid for lookup?

I think it would make the life for API users more easier if they could also use https://api.media.ccc.de/public/events/654331ae-1710-42e5-bdf4-65a03a80c614 and not only https://api.media.ccc.de/public/events/2806

**Comment by manno** [comment]
There is a `find` method which uses the uuid: https://github.com/voc/media.ccc.de/blob/master/app/controllers/public/events_controller.rb

**Comment by saerdnaer** [comment]
But this method is not accessible via HTTP, as https://github.com/voc/media.ccc.de/blob/master/config/routes.rb#L28-L32 only allows access on the index and show method.

Again, what should be the endpoint URL?
* https://api.media.ccc.de/public/events/find/654331ae-1710-42e5-bdf4-65a03a80c614
* or https://api.media.ccc.de/public/events/654331ae-1710-42e5-bdf4-65a03a80c614 ?

I would personally prefer the second case.
