### ISSUE TITLE
Add "directory listing" for torrent links

### ISSUE THREAD

**Issue by Kunsi** [voc/media.ccc.de#102]
Currently, directory Listing on cdn.media.ccc.de does only display video files, no torrent files [1].

There should be a page which contains only links to .torrent-files, so someone is able to use `wget -m` to get all torrent files (for example, to automatically add them to his/her torrent client).

[1] http://cdn.media.ccc.de/events/gpn/gpn16/h264-hd/

**Comment by saerdnaer** [comment]
adapted from https://events.ccc.de/congress/2015/wiki/Documentation#all-talks
`wget -nc -i <(curl http://cdn.media.ccc.de/events/gpn/gpn16/h264-hd/ | sed 's|.*<a href="\(.*mp4\)">.*|http://cdn.media.ccc.de/events/gpn/gpn16/h264-hd/\1.torrent|g' | grep torrent) `

**Comment by saerdnaer** [comment]
In the future (after switching from mirrorbrain to mirrorbits) we will generate .torrent files manually again, which results in regular files. And this files will also appear in the regular directory listing.
