### ISSUE TITLE
Conference data

### ISSUE THREAD

**Issue by Matthias84** [voc/media.ccc.de#13]
It would be nice, if there would be some more information about the conferences
* logo per conference (insteat of generic folder icon)
* Link to wikipedia
* ...

**Comment by derpeter** [comment]
Logo per conference could only be optional as many conference change there logo every year.
I agree that more conference related meta data would be great.

**Comment by Matthias84** [comment]
How about the most recent logo? If people are looking for a conference, it's possible that they noticed the current logo already somewhere and remind it again?

**Comment by manno** [comment]
There is already a logo per conference, the conference folder icon.

I can't imagine where this data (wikipedia link?) would be displayed. Someone with web design experience might help us out here. But couldn't you just google the conference name?

**Comment by Matthias84** [comment]
@all here you go  [media.ccc.de/app/views/frontend/shared/_embedshare.haml](https://github.com/voc/media.ccc.de/blob/c15d3370a310ad78e61feee3b093e9dffd459b84/app/views/frontend/shared/_embedshare.haml)

**Comment by manno** [comment]
I believe that link belongs into issue #7
