### ISSUE TITLE
Crowdsourcing metadata

### ISSUE THREAD

**Issue by Matthias84** [voc/media.ccc.de#15]
As some of my feature requests mean to (manually) extract / collect metadata, I recommend to make use of the crowd to do the necessary edits and keep the library up to date:
* tags
* URLs
* chapters
* quaility
* subtitles
* ...

**Comment by derpeter** [comment]
The way we handle user at the moment sadly only allows admin accounts which is not the right kind of account for crowdsourcing. This would require deeper changes in the backend.

**Comment by Matthias84** [comment]
Thats what I expected ;) On the other hand, if changing to an mainstream project (e.g. [Mediagoblin](http://mediagoblin.org/)) isn't an option, you will have to work on the inner engine :-/

**Comment by manno** [comment]
This would take weeks to develop. Last time I looked at mediagoblins source code it wasn't a good fit for our requirements.

**Comment by Matthias84** [comment]
@manno Well I'm not experienced with ruby, but doesn't most of the attributes can be derived from generic approaches? So implementing CRUD and permissions is rather a question of hours?

**Comment by manno** [comment]
Some of these fields we already have, others are more difficult. But to support chapters, subtitles and video qualities properly we'd have to improve the player code. Which means new data models, helpers, views, javascript, etc...
And what are these fields for? We can't just put more text on the pages, it has to match the existing design. Maybe the quality should be shown as an icon, in what views, where do we get the icons...

Sure, it's just more CRUD, in the admin backend interface and the authenticated API. And we'd probably want to export these fields in the public API.

And finally to actually crowd source this, we'd need a review system. So anonymous users don't mess with our live data. So we'd probably need data versioning, merging and conflict resolution too.

So what once was a simple admin backend interface turns into a content management system. At that point we might be better of with typo3....

**Comment by Matthias84** [comment]
Ok.... so how about using an external solution as [semantic mediawiki](http://semantic-mediawiki.org) to create this metadata externally and use the backend just for the video stuff itself? Then you can import the information from the wiki and recycle existing workflow (privileges, fields and types, reversions, ....) while keeping an loose coupling?
