### ISSUE TITLE
mixed content warning 

### ISSUE THREAD

**Issue by a-tze** [voc/media.ccc.de#2]
browsing on https://media.ccc.de/v/hs5_-_2013-08-24_10:00_-_beyond_lamp_-_daniel_hepper_-_1220

gives a mixed content warning. additionally (or it is the cause?) the postback to count the views is done on http://api.media.ccc.de (no https)

**Comment by manno** [comment]
Mixed content warning won't be fixed, because we serve videos via http. It's only a warning for passive content.

I'll fix the api URLs later.
