### ISSUE TITLE
Diaspora Oembed

### ISSUE THREAD

**Issue by manno** [voc/media.ccc.de#21]
Get whitelisted as Oembed provider with diaspora*

**Comment by svbergerem** [comment]
We whitelisted media.ccc.de as a trusted oEmbed provider. There is an issue with the display of your iframe:
![iframe size](https://cloud.githubusercontent.com/assets/3798614/12021430/0623197e-ad87-11e5-885e-37c3666b04ca.png)

You can test this with the following post:
https://pod.omgsrsly.net/posts/115737

**Comment by manno** [comment]
@svbergerem  I tried to fix that in e29c77aadae81a958a9aeae5ece2980cd5f517ea but it's not working yet.

**Comment by jhass** [comment]
Maybe you can just get rid of the explicit https://github.com/voc/media.ccc.de/blob/master/app/assets/stylesheets/frontend/styles.scss#L13 ?

**Comment by manno** [comment]
Thanks, that did work. The oembed URL supports maxwidth and maxheight.
