### ISSUE TITLE
Video not loading due to 302 redirect

### ISSUE THREAD

**Issue by frmwrk123** [voc/media.ccc.de#23]
The source URLs for the videos do not point to the final location. In Firefox Dev Edition I get the following error.

``
HTTP load failed with status 302. Load of media resource http://cdn.media.ccc.de/congress/2015/h264-hd-web/32c3-7228-en-NSA-Untersuchungsausschuss_Zwischen_Aufklaerungswillen_und_Mauern_aus_Schweigen.mp4 failed.
``

**Comment by manno** [comment]
http://cdn.media.ccc.de/ is a HTTP redirector, it should redirect you to a server in your vicinity.

I can't reproduce this with Chrome and Firefox nightly.

**Comment by frmwrk123** [comment]
For all those interested in the solution: I am using RequestPolicy and it blocks non-whitelisted requests. So I had to manually visit the mp4 in question (CDN link) and approve the requests. That way it works now for many mirrors. For the cases where it still shows the same error, I just have to reload for the CDN to use another mirror and therefore one I have already approved.
