### ISSUE TITLE
Include subtitles

### ISSUE THREAD

**Issue by ailin-nemui** [voc/media.ccc.de#24]
Hi, I know we have great live subtitles created at events like 32c3, it's sad that they are nowhere to be found once released. Even if they are imperfect would be very nice to have them available.

**Comment by derpeter** [comment]
we are working on that. It will happen as soon we got some final subtitles and some spare time

**Comment by ailin-nemui** [comment]
👍

**Comment by saerdnaer** [comment]
@ailin-nemui have a look at https://events.ccc.de/2016/01/10/call-for-subtitles/ to get some insight how the final subtitles for the recordings get produced.

**Comment by ailin-nemui** [comment]
thanks!
