### ISSUE TITLE
Switch between Languages in Player

### ISSUE THREAD

**Issue by MaZderMind** [voc/media.ccc.de#35]
The Player should have a switch to select one of the available web-Versions.
This should probably be worked upon the after-32c3 branch.

**Comment by saerdnaer** [comment]
Actually mediaelement.js has already an build in source chooser, which looks similar http://live.ber.c3voc.de/tests/avalon.html
It's implemented in https://github.com/johndyer/mediaelement/blob/master/src/js/mep-feature-sourcechooser.js which is not transpiled into the default minimized version ( https://github.com/johndyer/mediaelement/blob/master/Gruntfile.js#L51-L61 ) we are currently using. 

ToDos:
* [ ] update https://github.com/voc/media.ccc.de/blob/master/vendor/assets/javascripts/mediaelement-and-player.js to include sourcechooser by createing a new one with `grunt --features=playpause,stop,progress,time,volume,fullscreen,speed,tracks,contextmenu,skipback, sourcechooser`
* [ ] add other sources to <video>-Element, compare
``` 
<video id="player" class='video' controls height='360' poster='https://static.media.ccc.de/media/congress/2015/7225-hd_preview.jpg' width='640'>

    <source src='http://cdn.media.ccc.de/congress/2015/h264-hd-web/32c3-7225-de-Grundrechte_gelten_nicht_im_Weltall.mp4' type='video/mp4' data-quality="high" lang="de" title="mp4 hd de">
    <source src='http://cdn.media.ccc.de/congress/2015/h264-hd-web/32c3-7225-en-Grundrechte_gelten_nicht_im_Weltall.mp4' type='video/mp4' data-quality="high" lang="en" title="mp4 hd en">

    <source src='http://cdn.media.ccc.de/congress/2015/webm-hd/32c3-7225-de-en-Grundrechte_gelten_nicht_im_Weltall_webm-hd.webm' type='video/webm' data-quality="high" lang="de-en" title="webm hd de-en">
    <source src='http://cdn.media.ccc.de/congress/2015/webm-sd/32c3-7225-de-en-Grundrechte_gelten_nicht_im_Weltall_webm-sd.webm' type='video/webm' data-quality="low" lang="de-en" title="webm sd de-en">

    <source src='http://cdn.media.ccc.de/congress/2015/h264-hd/32c3-7225-de-en-Grundrechte_gelten_nicht_im_Weltall_hd.mp4' type='video/mp4' data-quality="high" lang="de-en" title="mp4 hd de-en">
    <source src='http://cdn.media.ccc.de/congress/2015/h264-sd/32c3-7225-de-en-Grundrechte_gelten_nicht_im_Weltall_sd.mp4' type='video/mp4' data-quality="low" lang="de-en" title="mp4 sd de-en">
</video>
```
(the `lang="*"` and `data-quality="low"` is not essential and actually part of another issue.)
* [ ] add sourcechooser to player features list, compare https://github.com/voc/media.ccc.de/commit/bea5e4478867f1347b66bf4c0406263efc5bc77d

**Comment by saerdnaer** [comment]
BTW: The current state regarding multi-track audio in the browsers. Testpage: http://live.ber.c3voc.de/tests/raw.html
All browsers select the audio track they think is correct, often based on the language setting of the browser or operating system. Only some of them actually allow you to switch between the tracks
* Safari (OSX and iOS): :white_check_mark: provides audio track selection UI if you let it. Currently at media.ccc.de the native UI is only shown at iOS (fullscreen mode) as we provide our own player bar.
* IE 11: :white_check_mark: Accourding to @florolf at the 32C3 infrastructure talk: provides audio track selection UI (haven't tested that) 
* Chrome: :red_circle: Doesn't provide audio track selection UI. (tested with current OS X)
* Firefox: :red_circle: Doesn't provide audio track selection UI. (tested with current OS X)

**Comment by saerdnaer** [comment]
Meenwhile @manno renders the language into the video-element sources, e.g. the source code for https://media.ccc.de/v/32c3-7102-crypto_ist_abwehr_ifg_ist_angriff looks like
```
<video class='video' controls='controls' data-id='2923' width='640' height='360' 
       poster='https://static.media.ccc.de/media/congress/2015/7102-hd_preview.jpg' >
   <source 
          data-lang='deu' 
          src='http://cdn.media.ccc.de/congress/2015/h264-hd-web/32c3-7102-de-Crypto_ist_Abwehr_IFG_ist_Angriff.mp4' 
          type='video/mp4'>
   <source 
          data-lang='deu-eng' 
          src='http://cdn.media.ccc.de/congress/2015/webm-hd/32c3-7102-de-en-Crypto_ist_Abwehr_IFG_ist_Angriff_webm-hd.webm' 
          type='video/webm'>
  <source 
          data-lang='eng' 
          src='http://cdn.media.ccc.de/congress/2015/h264-hd-web/32c3-7102-en-Crypto_ist_Abwehr_IFG_ist_Angriff.mp4' 
          type='video/mp4'>
   ...
</video>
```

**Comment by saerdnaer** [comment]
* Updated mediaelement player and added source sourcechooser module with https://github.com/voc/media.ccc.de/commit/e298cfd77117e8b46d6cbf3cfb9e9880fadb9ebc
* Added sourcechooser to player features list with https://github.com/voc/media.ccc.de/commit/1fa47bf147d731db690e8aa4ba605fd38999cd1c

**Comment by saerdnaer** [comment]
Wurde anscheinend, deployed: https://github.com/voc/media.ccc.de/issues/65 CSS Änderungen fehlen wohl noch, bzw. muss man noch machen.
