### ISSUE TITLE
Long titles should be shortened in the conference view

### ISSUE THREAD

**Issue by bjoern-r** [voc/media.ccc.de#38]
Test URL: https://media.ccc.de/c/32c3?sort=date
![image](https://cloud.githubusercontent.com/assets/5096000/12101113/4a3e400a-b333-11e5-97bd-3a73958c7e4d.png)

**Comment by bjoern-r** [comment]
Browser is Chrome (47.0.2526.106 (64-bit)) on OSX

**Comment by manno** [comment]
Tried to truncate the variables, but never found a good value. I wanted to put the description in the box, too. But with everything overflowing, I've no idea, maybe truncate title to 120 chars?

**Comment by MaZderMind** [comment]
The Title in the Example is just 104 Chars, so 120 seems to much. I'd propose truncating on the first space before the 90th character:
````ruby
truncate(title, length: 90, separator: ' ', omission: '…')
````

Alternatively we could truncate in CSS based on line-height but we wouldn't be able to add … to the end of the title then:
![screenshot from 2016-01-05 13 49 37](https://cloud.githubusercontent.com/assets/142237/12115505/36983f44-b3b3-11e5-83c7-523f972c63ca.png)
