### ISSUE TITLE
Link to streaming.media.ccc.de in empty conferences

### ISSUE THREAD

**Issue by MaZderMind** [voc/media.ccc.de#41]
When a conference is created but still empty, link to streaming.media.ccc.de with a sentence like "No Recordings have been released but you may find Livestreams or ReLive-Reocrdings on streaming.media.ccc.de"

**Comment by derpeter** [comment]
I would vote against this as already discussed in the irc.
Creating conferences before releasing starts has many drawbacks as media i.e. needs to know the schedule xml wich is usually not up to date at that time.
The only reason for creating empty conferences would be to be able to link to them but then we send user to empty places. 
Instead media should redirect links to not jet available conferences to the start page like https://media.ccc.de/c/foobar

If relay necessary media could show a banner like "this event is not yet available please come back later"

**Comment by manno** [comment]
media itself doesn't list empty conferences, if it does this is a bug. 

I understand the need for empty conference pages, however hard coding a link to streaming.media.ccc.de seems wrong for most folders on media. A configurable HTML block would be nice to have instead, but I'm closing this as wontfix. Pull requests are welcome, though :)
