### ISSUE TITLE
Directly connect to Elasticsearch from Ruby

### ISSUE THREAD

**Issue by MaZderMind** [voc/media.ccc.de#42]
Currently the Search is maintained as an external Service controlled by [two Perl-Scripts](https://github.com/voc/media-search-prototype/tree/master/server). This makes is harder to replicate the Setup during development and is also problematic in deployment.

I propose to move the Perl-Logic into the Rails-App. The importer could be a Rake-Task and the Search an API-Controller.

**Comment by manno** [comment]
I'm not sure how to do the import, never read the Perl script. However for connecting to  ES easily we could use https://github.com/elastic/elasticsearch-ruby

**Comment by MaZderMind** [comment]
The Import-Script just reads the events from the public api, decodes the json and throws them onto elasticsearch for indexing without doing any further processing. AFAIKS elasticsearch-ruby also exposes the `index` method, so it should be easy to implement the importer with it.
