### ISSUE TITLE
New API for releasing

### ISSUE THREAD

**Issue by manno** [voc/media.ccc.de#44]
* The new API should no longer download files and rely on already uploaded files instead.
* All requests should be possible with a guid instead of a database id
* ~~API keys may be limited to incoming folders and conferences~~

**Comment by MaZderMind** [comment]
I'm not quite sure if I understand your first point correctly. Wouldn't it be better to allow HTTP-Uploads of Recordings?

This way we could build a CLI-Tool to publish recordings.
Totally ACK with the other points.

**Comment by manno** [comment]
I'd use the existing upload accounts with scp/rsync support. You can still build a CLI tool. 

I think the files belong to the CDN, the app only links to them. I want to deploy mirrorbrain and the rails app onto different servers and there aren't 4TB free storage on the app server.

**Comment by MaZderMind** [comment]
ok, got it.

**Comment by manno** [comment]
Current consens on IRC is to build a separate upload-frontend with user management and http upload, thus making limited API keys here unnecessary.
