### ISSUE TITLE
RSS feeds: enclosure tag

### ISSUE THREAD

**Issue by MaZderMind** [voc/media.ccc.de#5]
Quote von ML-Mail
> Hallöchen,
> 
> Ich bin Mitentwickler einer Podcast-App und möchte nur mal darauf
> hinweisen, dass ihr <enclosure> falsch verwendet. Damit beziehe ich
> mich auf https://media.ccc.de/podcast-audio-only.xml
> 
> https://en.wikipedia.org/wiki/RSS_enclosure
> "length is its size in bytes", nicht Laufzeit in Minuten oder
> ähnliches. Dafür müsste man schon <itunes:duration> bemühen.
> 
> Grüße
> Martin

**Comment by mfietz** [comment]
Ich buzzer mich mal für Rückfragen und Ergebnis ein

**Comment by manno** [comment]
I believe this is fixed
