### ISSUE TITLE
Video with two audiotracks, the first one German, incorrectly displayed as English only

### ISSUE THREAD

**Issue by bwildenhain** [voc/media.ccc.de#52]
On
https://media.ccc.de/v/32c3-7146-hardware-trojaner_in_security-chips#download
WebM, WebM (HD) and MP4 are marked "EN" although the filename contains de-en and at least WebM really contains both audio tracks.

**Comment by saerdnaer** [comment]
@derpeter looks like your releasing script had a flaw... Should we change the language field manually in the admin gui?

**Comment by MaZderMind** [comment]
- Releasing Script ist seither 325× überarbeitet worden, insb. im Bereich der Sprachauswahlen
- Stichprobe auf anderen Talks durchführen
- Diesen Talk manuell Fixen, bei mehreren ggf. Bulk-Change

**Comment by MaZderMind** [comment]
fixed
