### ISSUE TITLE
public api: improve documentation 

### ISSUE THREAD

**Issue by saerdnaer** [voc/media.ccc.de#54]
Currently the public api isn't really good documented. 

For example I searched for ages what kind of query string I need to get an individual event. I wasn't aware I had to use the internal id of an event..., e.g. https://media.ccc.de/public/events/2935

Whats the normal way of getting this ID? Only through https://media.ccc.de/public/events/?

**Comment by TobiX** [comment]
AFAIR, the whole API is "discoverable" starting from https://media.ccc.de/public/conferences
