### ISSUE TITLE
Use title instead of conference acronym in the frontend

### ISSUE THREAD

**Issue by derpeter** [voc/media.ccc.de#56]
In the conference view the first headline is the conference slug not the conference title.
Usually on the title is from interest to the user but it is only the second, smaller headline.
We could probably remove the slug completely in the frontend

**Comment by saerdnaer** [comment]
I think you mean the conference acronym and not the conference slug, don't you?

**Comment by derpeter** [comment]
yes its the acronym

**Comment by manno** [comment]
The title is optional, so there needs to be some logic in place to fallback to acronym for h1.

Anyways this is the spot:
https://github.com/voc/media.ccc.de/blob/master/app/views/frontend/conferences/show.html.haml#L8

**Comment by MaZderMind** [comment]
Es sollen ggf. ach Secondary titles anzeigen
