### ISSUE TITLE
Diaspora share + between words instead of spaces.

### ISSUE THREAD

**Issue by paskalito** [voc/media.ccc.de#58]
Hi

I made a post on this alrady on t a closed issue which i think noone gets  notifications from anymore and i couldnt find a way to contact @manno so i made a new issue for that.

here is the problem:
https://github.com/voc/media.ccc.de/issues/7#issuecomment-168485436

**Comment by manno** [comment]
I think the [ Ruby method ]( http://apidock.com/ruby/v1_9_3_392/URI/encode_www_form_component/class ) works as expected. 

However the [ Javascript encodeURIComponent ]( https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent ) does not change white space into plus signs.

I could replace all `+` with `%20` though, would that help?

**Comment by paskalito** [comment]
YESS!, i think so because i got the expected result when i manually opened this url.

https://nerdpol.ch/bookmarklet?url=https%3A%2F%2Fshare.diasporafoundation.org%2Fabout.html&title=Share%20to%20diaspora*%20with%20as%20many%20spaces%20as%20possible

on "my" pod (nerdpol.ch)

very good idea.

**Comment by paskalito** [comment]
seems like you've fixed it right?
at least the issue seems to be gone for me :D 
thank you

**Comment by paskalito** [comment]
ok i just found out i have rights to close this issue i will so it then.

and a little picture for documentaiton purposes.

![bildschirmfoto vom 2016-02-03 14-48-19](https://cloud.githubusercontent.com/assets/8012793/12784073/4733196c-ca85-11e5-90dd-3c0397ed1629.png)


honors go to @manno for this commit https://github.com/voc/media.ccc.de/commit/134c33cd6e238e1b582a8ebf026105810d74f234 :D
