### ISSUE TITLE
Deutsche Sprachausgabe über englische Vorträge ausschaltbar

### ISSUE THREAD

**Issue by MarcelBulpr** [voc/media.ccc.de#59]
In englischen Vorträgen des cc Kongresses ist eine deutsche Sprachausgabe über das Video gelegt. die Möglichkeit dieses auszuschalten wäre sehr angenehm da die deutsche Sprachausgabe teilweise die meiner Meinung nach schlechtere alternative ist. Zurzeit schaue Ich englische Vorträge daher auf Youtube, würde es aber gerne auf media.ccc.de tun. 

Edit: z.B. hier: https://media.ccc.de/v/32c3-7386-crypto_wars_part_ii

**Comment by saerdnaer** [comment]
Wir haben das dieses Jahr eigentlich extra so gemacht, dass im Webinterface erst mal immer die Orginal-Sprache läuft. Demnächst soll dann auch noch ein Button zum Umschalten zwischen den verschiedenen Sprachversionen (vgl.  #35) kommen. 

Bei dem von dir ausgesuchten Beispiel spielt auch der Orginalton in Englisch, kannst du schauen ob das Problem bei dir immer noch auftritt? Falls ja: Welchen Web-Browser und Betriebssystem mit welcher System-Sprache benutzt du? 

Ansonsten kannst du dir im Download-Tab auch die entsprechende Sprachversion manuell aussuchen.

**Comment by saerdnaer** [comment]
Ich schließe das Ticket mal, da doppet.
