### ISSUE TITLE
Date-Format in Search-Results

### ISSUE THREAD

**Issue by MaZderMind** [voc/media.ccc.de#6]
Currently the Date-Format on the Search-Results-Page is too technical:
![screenshot from 2015-11-15 12 40 26](https://cloud.githubusercontent.com/assets/142237/11168592/1954dfa4-8b96-11e5-8923-85f21bca59bb.png)

The reason for this is, that the Elastic-Search just passes the date on as reported by the media.ccc.de-Api.

**Comment by MaZderMind** [comment]
One possible way to fix this would be to change the Perl-Script which translates between the incoming http-request and an elasticsearch-query.

Afaik it should be this script: https://github.com/voc/media-search-prototype/blob/master/server/search.pl

**Comment by manno** [comment]
@MaZderMind how would one change that script?
