### ISSUE TITLE
Anzeigefehler des "Source Chooser"

### ISSUE THREAD

**Issue by tnull** [voc/media.ccc.de#65]
Hallo!
ich bekomme die Videos des 32c3 auf media.ccc.de derzeit hauptsächlich in der deutschen Synchronfassung ausgeliefert. Zudem ist der "Source Chooser" des Players nach rechts verrückt, sodass ich ihn nicht bedienen kann (Sowohl bei Firefox, Chrome, wie auch bei Safari auf OS X), siehe 
[Screenshot](https://cloud.githubusercontent.com/assets/521467/13160900/c24f3614-d69a-11e5-8051-0608433ba134.png).
Viele Grüße.

**Comment by saerdnaer** [comment]
Hmm, den Bug hatte ich ganz vergessen.

@MaZderMind: Weißt du noch was du mit https://github.com/voc/media.ccc.de/blob/master/app/assets/stylesheets/frontend/styles.scss#L196-L198 bezwecken wolltest?

**Comment by saerdnaer** [comment]
@manno Kannst du das neue CSS file deployen?
