### ISSUE TITLE
Player size

### ISSUE THREAD

**Issue by saerdnaer** [voc/media.ccc.de#66]
Aktuell steht die mittlere Spalte die max-width auf 700px, mit dem 15px padding bleibt noch 670px Platz fuer den Player. Der ist im <video> tag auf 640x360px Breite beschränkt, die Box drumrum mit den Tabs ist aber 670px und nicht 640px. Durch  https://github.com/voc/media.ccc.de/commit/db961d9692961fa63ed691c81a1c88a687d05e19 fällt das ganze jetzt wieder auf.

Aber eigentlich macht das so gar keinen Sinn. Eigentlich sollte man da einen responsive Ansatz wählen, bei dem die Playergröße in festen Schritten auf Basis der verfügbaren Bildschirmgröße anpasst. 

Bei Player von Youtube sind die Stufen z.B.  1280x720, 854x480, 640x360, 426x240. 1920x1080 gibts erst wenn man den Full-Screen Button drückt.

Bei uns bekommt man aktuell gleich 1920x1080 was dann vom Browser erst mal auf 670x377px bzw. jetzt wieder auf 640x360px heruntergescaled werden muss. Bei SD-Only releases sind es dann 1024x576px.

Ich würde vorschlagen das wir in Zukunft zwischen folgenden Auflösungen umschalten: 1920x1080, 1280x720, 1024x576, 854x480, 640x360, darunter ggf. einfach wieder das stufenlose anpassen durch width=100%. Die Größe der Box sollte sich auch daran anpassen (größer und kleiner werden), wenn man grade im Video-Tab ist.

Note to self: http://stackoverflow.com/a/20132689/521791

**Comment by line-o** [comment]
Wie kommen die Stufen zustande? Sind das Videoauflösungen die ihr bereitstellt?
Sonst muss ja trotzdem herunterskaliert werden. Oder ist das performanter weil diese Stufen ganzzahlig/ leichter zu berechnen sind?
Wovon ist der Sprung zwischen den Stufen abhängig? 
Wenn die Fensterbreite (`window.width`) die Antwort ist, sind media-queries die Lösung deines Problems.
Sonst sind wahrscheinlich CSS-Klassen mit den entsprechenden Werten für Höhe und Breite ein guter Ansatz. Die kann man dann mit JavaScript oder beim ausliefern dem Player-Element zuweisen.

**Comment by line-o** [comment]
Hab jetzt noch mal den SO-Link von oben verfolgt. Es gibt eine media-queries jetzt auch in der JS-Welt `window.matchmedia` (quelle: [Sitepoint.com](http://www.sitepoint.com/javascript-media-queries/) ). Das wird in den aktuellen Browsern [Unterstützt](http://caniuse.com/#search=matchmedia).

**Comment by saerdnaer** [comment]
https://css-tricks.com/rundown-of-handling-flexible-media/#article-header-id-5

**Comment by saerdnaer** [comment]
Vorschlag von Texec: Noch einen schwarzen Hintergrund der bis zum Rand des Fensters geht (vgl. Theater Mode). Ggf. auch fürs Menü.

**Comment by saerdnaer** [comment]
fixed with https://github.com/voc/media.ccc.de/pull/90
