### ISSUE TITLE
OpenGraph for previews

### ISSUE THREAD

**Issue by Matthias84** [voc/media.ccc.de#8]
Hi one reason why people prefer sharing the VOC youtube videos is, that youtube supports embedded previews / playback. While I think media.ccc.de wouldn't get the  attention to get an listet [oembed](http://oembed.com)-Provider, you can still offer preview images via [opengraph](ogp.me), as for example every wordpress-instance does.

**Comment by manno** [comment]
Added opengraph tags for the event page.
