### ISSUE TITLE
Show newest videos

### ISSUE THREAD

**Issue by Matthias84** [voc/media.ccc.de#9]
I'm following media via RSS, so I get an push if there is something new. Unfortunatly that view on the videos isn't available via browsing the website

**Comment by manno** [comment]
Most of the time we release whole conferences, up to 60 videos at once. So this view would be more like a 'recent conferences'. I'm not convinced, we already support three navigations: 'search', 'tag' and 'folders'. 

Unless anyone is interested, I'd reject this issue.

**Comment by manno** [comment]
New /recent view kind of solves this.
